# Generated by Django 2.2.1 on 2019-05-27 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
