# Generated by Django 2.2.1 on 2019-05-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0003_graphicdesign_mobileapplication_webdesign'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditTool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Araclar')),
            ],
            options={
                'verbose_name': 'Araclar',
                'verbose_name_plural': 'Araclar',
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Teknolojiler')),
            ],
            options={
                'verbose_name': 'Teknologi',
                'verbose_name_plural': 'Teknolojiler',
            },
        ),
        migrations.AlterField(
            model_name='graphicdesign',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Grafik Tasarım'),
        ),
        migrations.AddField(
            model_name='graphicdesign',
            name='editTool',
            field=models.ManyToManyField(to='serviceapp.EditTool', verbose_name='program'),
        ),
    ]
