# Generated by Django 2.2.1 on 2019-05-25 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, verbose_name='Sehir')),
                ('district', models.CharField(max_length=50, verbose_name='mahalle')),
                ('street', models.CharField(max_length=50, verbose_name='sokak')),
                ('home', models.CharField(max_length=50, verbose_name='Ev No')),
            ],
            options={
                'verbose_name': 'Adres',
                'verbose_name_plural': 'Adresler',
            },
        ),
        migrations.CreateModel(
            name='BankModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Banka')),
                ('branch', models.CharField(max_length=50, verbose_name='Sube')),
                ('account', models.TextField(max_length=255, verbose_name='Hesap No')),
            ],
            options={
                'verbose_name': 'Banka Hesabi',
                'verbose_name_plural': 'Banka Hesaplari',
            },
        ),
        migrations.CreateModel(
            name='CompanyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Sirket ')),
                ('company_reference', models.IntegerField(verbose_name='Referans')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmain.AddressModel', verbose_name='Adres')),
                ('bank', models.ForeignKey(max_length=250, on_delete=django.db.models.deletion.CASCADE, to='appmain.BankModel', verbose_name='Banka Hesap')),
            ],
            options={
                'verbose_name': 'Sirket',
                'verbose_name_plural': 'Sirketler',
            },
        ),
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.FloatField(max_length=10, verbose_name='Birim Fiyat')),
                ('email', models.EmailField(max_length=100, verbose_name='E posta')),
                ('website', models.URLField(max_length=100, verbose_name='web')),
            ],
            options={
                'verbose_name': 'iletisim',
                'verbose_name_plural': 'iletisim Bilgileri',
            },
        ),
        migrations.CreateModel(
            name='DepartmentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Departmen')),
            ],
            options={
                'verbose_name': 'Departman',
                'verbose_name_plural': 'Departmanlar',
            },
        ),
        migrations.CreateModel(
            name='IndustryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Sektor')),
            ],
            options={
                'verbose_name': 'Sektor',
                'verbose_name_plural': 'Sektorler',
            },
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderType', models.IntegerField(verbose_name='Teklif tipi')),
            ],
            options={
                'verbose_name': 'Teklif',
                'verbose_name_plural': 'Teklifler',
            },
        ),
        migrations.CreateModel(
            name='PriceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_wage', models.FloatField(verbose_name='Birim Fiyat')),
            ],
            options={
                'verbose_name': 'Fiyat',
                'verbose_name_plural': 'Fiyatlar',
            },
        ),
        migrations.CreateModel(
            name='TaxModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administration', models.CharField(max_length=100, verbose_name='Vergi Dairesi')),
                ('taxNo', models.BigIntegerField(verbose_name='Vergi No')),
            ],
            options={
                'verbose_name': 'Vergi',
                'verbose_name_plural': 'Vergi Bilgileri',
            },
        ),
        migrations.CreateModel(
            name='ServiceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Hizmet')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmain.DepartmentModel', verbose_name='Departman')),
            ],
            options={
                'verbose_name': 'Hizmet',
                'verbose_name_plural': 'Hizmetler',
            },
        ),
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_firstname', models.CharField(max_length=50, verbose_name='Ad')),
                ('emp_lastname', models.CharField(max_length=50, verbose_name='Soyad')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmain.CompanyModel', verbose_name='Sirket')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmain.DepartmentModel', verbose_name='Departman')),
                ('price', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appmain.PriceModel', verbose_name='Ucret')),
            ],
            options={
                'verbose_name': 'Calisan',
                'verbose_name_plural': 'Calisanlar',
            },
        ),
        migrations.AddField(
            model_name='companymodel',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmain.IndustryModel'),
        ),
        migrations.AddField(
            model_name='companymodel',
            name='tax',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmain.TaxModel', verbose_name='Vergi Dairesi'),
        ),
    ]
