# Generated by Django 2.2.1 on 2019-05-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymodel',
            name='department',
            field=models.ManyToManyField(to='appmain.DepartmentModel', verbose_name='Departman'),
        ),
    ]
